//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class RefillHistory
    {
        public decimal Quantity { get; set; }
        public System.DateTime Datetime { get; set; }
        public string GasStationID { get; set; }
    
        public virtual GasStation GasStation { get; set; }
    }
}
