//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnderInvestigation
    {
        public System.DateTime IssueDatetime { get; set; }
        public string GasStationId { get; set; }
        public string InvestigatorId { get; set; }
    
        public virtual GasStation GasStation { get; set; }
        public virtual Investigator Investigator { get; set; }
    }
}
